services:
  - name: backend
    type: web
    name: cmdr-backend
    env: docker
    rootDir: backend
    plan: free

  - name: frontend
    type: static
    rootDir: frontend
    buildCommand: cp -R static templates/static && npm install && npm run build
    staticPublishPath: templates
    plan: free